title: Koala
author: Tasmeehur
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I don't think writing a cool description will help my ego overcome the overwhelming sense of surface level knowledge.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
